title: YutixCode
author: Author
email: your-email@example.com
description: A clean and responsive jekyll theme

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: dark

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
