title: YutixCode
author: Yutix
email: nouhimetv@gmail.com
description: "Situs yang dirancang khusus untuk anak dibawah 12 tahun."

date_format: "%F"
blog_theme: dark
markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
