# Site settings
title: "YutixCode"
description: "Website khusus anak umur dibawah 15 tahun"
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: "https://yutixcode.github.io"
author: "YutixCode"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
#google_analytics:
#disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
