title: Mint
author: Author
email: your-email@example.com
description: A clean and responsive jekyll theme

github_username: aidewoode
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: auto

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
