# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - issue.md
  - about.md

footer: 'View on <a href="https://github.com/kiinlam/vue-examples">Github</a>'

style: light # dark (default) or light

plugins:
  - jekyll-seo-tag
